apiVersion: v1
kind: PersistentVolume

metadata:
  name: navidrome-music-pv

spec:
  capacity:
    storage: 100Gi

  accessModes:
    - ReadWriteOnce

  persistentVolumeReclaimPolicy: Retain

  storageClassName: manual

  hostPath:
    path: /mnt/storage/music
