apiVersion: v1
kind: Service

metadata:
  name: navidrome

spec:

  selector:
    app: navidrome

  ports:

  - port: {{ .Values.service.port }}
    targetPort: 4533

  type: {{ .Values.service.type }}
