auth:
  rootPassword: ChangeRootPassword123!
  database: nextcloud
  username: nextcloud
  password: ChangeNextcloudPassword123!

architecture: standalone

primary:
  persistence:
    enabled: true
    size: 20Gi

  resources:
    requests:
      cpu: 100m
      memory: 256Mi

    limits:
      cpu: 1000m
      memory: 1Gi

metrics:
  enabled: false
